# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='creator',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
